limit_req_zone $binary_remote_addr zone=melotools_general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=melotools_heavy:10m rate=10r/m;
limit_conn_zone $binary_remote_addr zone=melotools_connections:10m;

